### PR TITLE
Implemented `JWT` authorization to api endpoints

### LINKED ISSUE #24: Implement JWT to api endpoints
## Description

- Add `JWT` to required api endpoint ( `/api/classes` , `/api/quizzes` etc..)

### PR DESCRIPTION
**Pull request by NikhilSharma03**
#### This PR Fixes #24 

- [x] added `VeriftUserUsingJWT` method
- [x] added `JWTVerifiedData` struct to return
- [x] added Jwt security to `/api/users` routes
- [x] added Jwt security to `/api/quizzes` routes
- [x] added Jwt security to `/api/classes` routes
- [x] Updated Readme.md : `folder structure` and `new golang avatar`.. lol :rofl:

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
Tests are failing since JWT is placed now :thinking:

**Review by jinwoo1225 — APPROVED** [review]
LGTM🚀🚀

**Comment by jinwoo1225** [comment]
@NikhilSharma03 wish i can fix it in next pr 🤣

**Comment by NikhilSharma03** [comment]
@jinwoo1225 That would be great. :rofl:

**Pull request merged**
