### PR TITLE
End to End Testing with In-Memory MongoDB Server

### PR DESCRIPTION
**Pull request by jinwoo1225**
#End to End Testing!
Finally added e2e testing to our project.
you can notice we have to serve our database to router due to limit of using only environment variable to control our database :)
## How?
- create `*testName*_e2e_test.go` to your desired e2e test
- you can import my own  MockDatabase method in `E2E_test.go` or create your own
- use http and httptest to test and use assert package to further testing

> Good Luck 😁

### CODE REVIEW

**Review by NikhilSharma03 — APPROVED** [review]
This is cool. Great Work :rocket:

**Comment by NikhilSharma03** [comment]
@jinwoo1225 Let's have all our tests in one `tests` folder

**Comment by jinwoo1225** [comment]
@NikhilSharma03 of course~~ i'll merge it first!

**Comment by NikhilSharma03** [comment]
@jinwoo1225 Thanks :+1:

**Pull request merged**
