### PR TITLE
JWT Implementation

### LINKED ISSUE #18: JWT
## Description

- Implement `JWT`

### PR DESCRIPTION
**Pull request by NikhilSharma03**
### This PR Fixes #18 

- [x] added json `helpers` and `middlewares` handlers
- [x] add refresh token

### CODE REVIEW

**Comment by NikhilSharma03** [comment]
## Changes

- Added new `/api/refresh_token` route to get new `access token`
- added `GenerateAccessToken`, `GenerateRefreshToken`, `ValidateToken` handlers

**Comment by NikhilSharma03** [comment]
@jinwoo1225 Now is the correct time to finish `API reference` (since most of routes and JWT in implemented) so we can cover all other `api endpoints`. What do you think?

**Comment by jinwoo1225** [comment]
> @jinwoo1225 Now is the correct time to finish `API reference` (since most of routes and JWT in implemented) so we can cover all other `api endpoints`. What do you think?

Yeap, we can do right away!

**Review by jinwoo1225 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
